### ISSUE TITLE
rtbasic 1.0c clean data entry from original manual

### ISSUE THREAD

**Issue by stanleyruppert** [linuxha/RT68mx#1]
rtbasic 1.0c clean data entry from original manual
Typed in and validated code from manual. one line missing from manual, copied from existing 1.0C version notes I had.
[rtbasic10c_s19.txt](https://github.com/linuxha/RT68mx/files/14398824/rtbasic10c_s19.txt)

**Comment by linuxha** [comment]
Excellent! I've added it to the repos. I hope to begin working on disassembling it soon. Notes and progress will be added to the repos. Even if the progress is partial. This will keep local problems from being outside problems.
