### ISSUE TITLE
Bug in RTEDIT $04F0 record - typo from using manual s19 listing - found recompiling with ABASIC.

### ISSUE THREAD

**Issue by stanleyruppert** [linuxha/RT68mx#5]
Now that I have ABASIC running, I recompiled the Basic source for RTEDIT as a test (of both ABASIC and RTEDIT data entry).
The compilation produced a byte exact copy of RTEDIT binary/S19 with the exception of double byte error in $04F0 record.
Once again, the double byte error produced the same s19 checksum :(  boo.

Old record: S11304F0 30 7E050A4FC601 07 6197604FC601D75B7E

Should be:  S11304F0 60 7E050A4FC601 D7 6197604FC601D75B7E

This is consistent with the original manual listing.
![IMG_4573 copy](https://github.com/user-attachments/assets/34bbd409-7973-4021-885a-cf4acfd3a231)

**Comment by linuxha** [comment]
Updated and pushed. Thanks for finding this. I'm a bit distracted lately. :-)
